/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cube.glb')
  return (
    <group ref={group} {...props}>
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} position={[0, 3.58, 0]} />
      <mesh material={materials.Material} geometry={nodes.Cube001.geometry} position={[0, 4.89, -0.88]} />
    </group>
  )
}

useGLTF.preload('/cube.glb')
