/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/html.glb')
  return (
    <group ref={group} {...props}>
      <mesh material={materials['SVGMat.003']} geometry={nodes.Outer.geometry} position={[0, 4.67, -0.2]} />
      <mesh material={materials['SVGMat.004']} geometry={nodes.Innter.geometry} position={[0, 4.67, -0.02]} />
      <mesh
        material={materials['SVGMat.005']}
        geometry={nodes['5'].geometry}
        position={[0, 4.67, 0.32]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/html.glb')
