/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/html.glb')
  return (
    <group ref={group} {...props}>
      <mesh
        material={materials.OuterC}
        geometry={nodes.outer.geometry}
        position={[0.06, 9.47, 21.19]}
        rotation={[0, -0.05, 0]}
        scale={[9.05, 9.05, 9.05]}
      />
      <mesh
        material={materials.InnerC}
        geometry={nodes.inner.geometry}
        position={[-0.02, 9.47, 22.79]}
        rotation={[0, -0.05, 0]}
        scale={[9.05, 9.05, 9.05]}
      />
      <mesh
        material={materials.Five}
        geometry={nodes.five.geometry}
        position={[-0.04, -9.59, 23.15]}
        rotation={[Math.PI / 2, 0, 0.05]}
        scale={[4.08, 4.08, 4.08]}
      />
    </group>
  )
}

useGLTF.preload('/html.glb')
