/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/html5.glb');
  return (
    <group ref={group} {...props}>
      <group rotation={[0, -0.04, 0]}>
        <mesh
          material={materials.darkOrange}
          geometry={nodes.curve_0.geometry}
        />
        <mesh material={materials.orange} geometry={nodes.curve_1.geometry} />
        <mesh material={materials.white} geometry={nodes.curve_2.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload('/html5.glb');
