/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/html.glb');
  return (
    <group ref={group} {...props}>
      <group position={[0, 4.58, 0]} scale={[0.36, 0.36, 0.36]}>
        <mesh material={materials.Outer} geometry={nodes.Curve_0.geometry} />
        <mesh material={materials.Inner} geometry={nodes.Curve_1.geometry} />
        <mesh material={materials.Five} geometry={nodes.Curve_2.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload('/html.glb');
