/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/reactHtml.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, 9, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.19, 1.19, 1.19]}
        userData={{ name: 'React-Background' }}>
        <mesh material={materials.darkBlue} geometry={nodes.reactBackground.geometry} />
        <mesh material={materials.cyan} geometry={nodes.reactBackground_1.geometry} />
      </group>
      <mesh
        material={materials['Material.003']}
        geometry={nodes.appBackground.geometry}
        position={[-18.49, 9, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.67, 8, 8]}
        userData={{ name: 'appBackground' }}
      />
      <mesh
        material={materials['Material.002']}
        geometry={nodes.Cube.geometry}
        position={[-18.64, 8.7, 1.42]}
        scale={[4.62, 4.62, 0.51]}
        userData={{ name: 'Cube' }}
      />
      <mesh
        material={materials['Material.001']}
        geometry={nodes.Cube001.geometry}
        position={[-18.64, 8.7, 0.85]}
        scale={[5.69, 5.69, 0.43]}
        userData={{ name: 'Cube.001' }}
      />
      <mesh
        material={nodes.Text.material}
        geometry={nodes.Text.geometry}
        position={[-18.62, 5.87, 1.96]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.85, 1.85, 1.85]}
        userData={{ name: 'Text' }}
      />
      <group position={[8.75, 1.08, 0]} scale={[2.31, 2.31, 2.31]} userData={{ name: 'HTML5' }}>
        <mesh material={materials.outerOrange} geometry={nodes.html5.geometry} />
        <mesh material={materials.innerOrange} geometry={nodes.html5_1.geometry} />
        <mesh material={materials.five} geometry={nodes.html5_2.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/reactHtml.glb')
